;;; gn-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from gn-mode.el

(autoload 'gn-mode "gn-mode" "\
Major mode for editing GN (generate ninja) config files.

\\<gn-mode-map>

(fn)" t)
(register-definition-prefixes "gn-mode" '("gn-"))

;;; End of scraped data

(provide 'gn-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gn-mode-autoloads.el ends here
