;;; flymake-popon-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from flymake-popon.el

(autoload 'flymake-popon-mode "flymake-popon" "\
Toggle show Flymake diagnostics on cursor hover.

This is a minor mode.  If called interactively, toggle the
`Flymake-Popon mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `flymake-popon-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-flymake-popon-mode 'globalized-minor-mode t)
(defvar global-flymake-popon-mode nil "\
Non-nil if Global Flymake-Popon mode is enabled.
See the `global-flymake-popon-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-flymake-popon-mode'.")
(custom-autoload 'global-flymake-popon-mode "flymake-popon" nil)
(autoload 'global-flymake-popon-mode "flymake-popon" "\
Toggle Flymake-Popon mode in all buffers.
With prefix ARG, enable Global Flymake-Popon mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Flymake-Popon mode is enabled in all buffers where
`flymake-popon-mode' would do it.

See `flymake-popon-mode' for more information on Flymake-Popon mode.

(fn &optional ARG)" t)
(register-definition-prefixes "flymake-popon" '("flymake-popon-"))

;;; End of scraped data

(provide 'flymake-popon-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-popon-autoloads.el ends here
